'use client';

import { useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { useTranslations } from 'next-intl';
import { IconLoader2, IconPlus } from '@tabler/icons-react';
import { cn } from '@/lib/cn';
import { buttonClasses } from '@/components/ui/Button';
import { createMyCourseAction } from '@/lib/teacher/studio-actions';

const inputCls = 'w-full rounded-lg border border-ink/15 bg-paper px-3 py-2 text-sm text-ink';

/**
 * The studio's "Nouvo fòmasyon" form (Task C3-T4) — mirrors
 * components/admin/content/CreateCourseForm.tsx, but simpler: no manual
 * code field (auto-generated by `createMyCourseAction` → `writeOps.
 * createCourse`'s existing `getNextCourseCode()`/`slugify()` logic), and the
 * new course is owned by the SIGNED-IN teacher, always created as
 * `status: 'draft'` (never directly publishable — see submitMyCourseForReviewAction).
 */
export function CreateMyCourseForm() {
  const t = useTranslations('teach.studio.create');
  const router = useRouter();
  const [pending, start] = useTransition();
  const [titleHt, setTitleHt] = useState('');
  const [titleFr, setTitleFr] = useState('');
  const [price, setPrice] = useState('');
  const [err, setErr] = useState<string | null>(null);

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        start(async () => {
          setErr(null);
          const res = await createMyCourseAction({
            title_ht: titleHt.trim(),
            title_fr: titleFr.trim(),
            priceCents: Math.round((Number(price) || 0) * 100),
          });
          if (res.ok && res.slug) router.push(`/enseigner/studio/cours/${res.slug}/editer`);
          else setErr(res.message === 'title_required' ? t('titleRequired') : t('error'));
        });
      }}
      className="max-w-2xl space-y-4 rounded-xl border border-ink/12 bg-paper-light p-5"
    >
      <p className="text-[11px] leading-snug text-graphite/60">{t('help')}</p>
      <div className="grid gap-3 sm:grid-cols-2">
        <label className="block">
          <span className="mb-1 block font-mono text-[10px] uppercase tracking-wide text-ink/55">{t('titleHt')}</span>
          <input value={titleHt} onChange={(e) => setTitleHt(e.target.value)} className={inputCls} />
        </label>
        <label className="block">
          <span className="mb-1 block font-mono text-[10px] uppercase tracking-wide text-ink/55">{t('titleFr')}</span>
          <input value={titleFr} onChange={(e) => setTitleFr(e.target.value)} className={inputCls} />
        </label>
      </div>
      <label className="block">
        <span className="mb-1 block font-mono text-[10px] uppercase tracking-wide text-ink/55">{t('price')}</span>
        <span className="flex items-center gap-1 font-mono text-sm text-ink/55">
          $<input type="number" min="0" value={price} onChange={(e) => setPrice(e.target.value)} className={cn(inputCls, 'w-24')} />
        </span>
      </label>
      <p className="font-mono text-[10px] text-ink/45">{t('draftNote')}</p>
      {err && <p className="font-mono text-[11px] text-stampred">{err}</p>}
      <button type="submit" disabled={pending || (!titleHt && !titleFr)} className={cn(buttonClasses('primary', 'md'), 'text-xs')}>
        {pending ? <IconLoader2 size={15} className="animate-spin" /> : <IconPlus size={15} />}
        {t('submit')}
      </button>
    </form>
  );
}
